name: PR - Quality Code - SonarCloud
on:

  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  sonarCloudScan:
    name: SonarCloud Analysis
    uses: cegid/vsb-devops/.github/workflows/template-sonarcloud-javascript.yaml@v4.1.0
    with:
      PROJECT_KEY: cegidgroup_vsb-cds-react
      SONAR_EXCLUSIONS: ''
      EXTRA_SONAR_OPTIONS: ''
    secrets:
      VSB_SONAR_TOKEN: ${{ secrets.VSB_SONAR_TOKEN}}
      HUGE_ICONS_AUTH_TOKEN: ${{ secrets.HUGE_ICONS_AUTH_TOKEN }}